version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"

  # Maintain dependencies for the dev container
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:30"
